spring:
  datasource:
    url: jdbc:postgresql://db.bjeqghpesboidxkvpqjw.supabase.co:5432/postgres
    username: postgres
    password: ftpiptf0group06

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: 'create-drop'

jwt:
  secret: fghdkf689dfghd56dgbhs

report:
  url: http://172.30.5.51:8080/api/log/

order:
  url: http://172.19.128.1:8080/api/order

api:
  key: abb2f34c-286e-4260-b438-a7755a421423

marketData:
  url1: http://*****/
  url2: http://*****/
  both: http://*****/

exchange:
  url1: https://exchange.matraining.com/
  url2: https://exchange1.matraining.com/

redis:
  hostname: 167.99.202.174
  port: 6379
  marketdatachannel: MarketDataChannel